### ISSUE TITLE
Required Types

### ISSUE THREAD

**Issue by austenstone** [abdulk1/Leaflet.RotatedMarker#1]
The types `@types/leaflet` are required but may cause issues with webpack when trying to import modules at a global scope.

I am using Angular and some leaflet plugins do not have types and therefore I create my own type in `typings.d.ts`. When `npm i leaflet-marker-rotation` I get type errors because of the required types that are automatically installed.

I would prefer for `@types/leaflet` to be optional.

**Comment by abdulk1** [comment]
thanks for bringing this up. We can certainly put the Leaflet types as optionalDependencies. I'll be sure to publish a new version over the weekend
